export enum Industry {
  HEALTHCORE = "HEALTHCORE",
  AGRIBUSINESS = "AGRIBUSINESS",
  TRANSPORTATION_MOBILITY = "TRANSPORTATION_MOBILITY",
  TECHNOLOGY = "TECHNOLOGY",
}

export enum CompanyStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  CLOSED = "CLOSED",
  TRIAL = "TRIAL",
  CANCELLED = "CANCELLED",
}

export enum UserType {
  GLOBAL_ADMIN = "GLOBAL_ADMIN",
  COMPANY_ADMIN = "COMPANY_ADMIN",
  EMPLOYEE = "EMPLOYEE",
}

export enum Segment {
  LABORATORY = "LABORATORY",
  HOSPITAL = "HOSPITAL",
  MEDICAL_METALLURGY = "MEDICAL_METALLURGY",
  ANIMAL_HEALTH = "ANIMAL_HEALTH",
  VEHICLE_INSPECTION = "VEHICLE_INSPECTION",
  VEHICLE_REGISTRATION = "VEHICLE_REGISTRATION",
  DRIVING_SCHOOL = "DRIVING_SCHOOL",
}

export enum BranchStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  OBSOLETE = "OBSOLETE",
}
